### PR TITLE
04 showing porfolio distribution

### PR DESCRIPTION
**Pull request by fedefailla18**

### CODE REVIEW

**Comment by fedefailla18** [comment]
This PR has integrity with the FE. So now we are able to see the portfolio on the portfolio-importer-web.

**Comment by facum15** [comment]
como vamos?

**Comment by facum15** [comment]
no veo avances en este PR, alguien del team puede revisar si hay que mergear estos cambios o eliminamos este PR?

**Comment by fedefailla18** [comment]
This PR is meant to do a quick view of holdings and generate a Portfolio view based on the input done for users. Basically you need to add manually every symbol with its amount. Then in the FE you are gonna be able to see, at the price of today what percentage represents

**Pull request merged**
